language: java
branches:
  only:
  - master
  - develop
install: true
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
script:
- git clone -b master https://github.com/nablarch/nablarch-ci-script.git $HOME/build-script/
  && chmod +x $HOME/build-script/travis-ci/*.sh
- $HOME/build-script/travis-ci/setup-oracle-jdk6.sh
- $HOME/build-script/travis-ci/prepare_travis_settings.sh
- $HOME/build-script/travis-ci/build-nablarch.sh -m deploy -p ci,dev-deploy
- $HOME/build-script/travis-ci/upload-test-report.sh -p dev-deploy
notifications:
  slack:
    secure: CGjAP85eadOMDBMI/tdl2JnMDoT0o6Rr9q0I32yBL+Qvs9AaW3gN68zOi5Lo+D+V6Mo9GUhqiihqdXQDcbuXbY/x1Sx1os2eiALIdwhjV2crsXO+k0YLWugFWdpoDL03YlxAaYT8VShJyuorrd9sRde9ohM1MKLiuW7KhkIWbBFJJLxsk52bh8mfv8RSSHE0ny/S2cK8klOpSlVvR1qOxy5e2lLzdYl1HEnfPnzwaXwDFsI394ROJDZwhvm8UFqdcTNyGgCuUIaiI4kuoayzb4I+BUeyv1c3ZEkPKlVDqpc8wwQK8rOjlmulyjLvpQF1PEu2x6ZZja1OzHl6aF56Pd3rMN5Nm/sSWJx9Ue6PO0bD+KNLWyzrb3BygLM6kPF14AW2d//+spPR0w05+s0zk7AoU3hjeYKYWEQBH50gPzcWciwEfMqXMjwz/slPToAOQn8b2WjKl+nAWN00L86bTDhet8ynPS0w1WldTpybjbni/UmeX8FPp/TIkSCkmusQvmtONuruafOxouLo3pckIx3gp3U6Ro+3f8HW0eRMp5c87ZOZQ8W0DJGALyY7ZQHiNpCm4uK41GImDGx2wA6qGE3UEp9Rorb2h5TAR4JUZjkE3RDiWaufnOyuXqW9Kzw6K8VxEGXPFkyOFPlOPqX4N8K3KpwhtVUmiZSFjrP6/0c=
